version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: hunt-the-wumpus-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: huntthewumpus
      MYSQL_USER: wumpus_user
      MYSQL_PASSWORD: wumpus_pass
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
